### ISSUE TITLE
Python3 direct execution

### ISSUE THREAD

**Issue by improve100** [SL-RU/stm32-emacs#1]
Scanning dependencies of target ('Test2','.elf
[  4%] Building C object CMakeFiles/('Test2','.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o
clang: error: no such file or directory: ', -mthumb'
clang: error: no such file or directory: ', '
clang: error: invalid float ABI '-mfloat-abi=hard, '
clang: error: invalid float ABI '-mfloat-abi=hard, '
CMakeFiles/('Test2','.elf.dir/build.make:62: recipe for target 'CMakeFiles/('Test2','.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o' failed
make[2]: *** [CMakeFiles/('Test2','.elf.dir/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/('Test2','.elf.dir/all' failed
make[1]: *** [CMakeFiles/('Test2','.elf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Compilation exited abnormally with code 2 at Tue Jun 26 10:43:33

**Comment by improve100** [comment]
CUBE project name: ('Test2', '
CUBE MCU: ', 'STM32F411RETx', '
CUBE CFLAGS: ', '-mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard', '
CUBE DEFs: ', ' -D__weak=""__attribute__((weak))"" -D__packed=""__attribute__((__packed__))"" -DUSE_HAL_DRIVER -DSTM32F41
1xE -D__weak=""__attribute__((weak))"" -D__packed=""__attribute__((__packed__))"" -DUSE_HAL_DRIVER -DSTM32F411xE -D__weak
=""__attribute__((weak))"" -D__packed=""__attribute__((__packed__))"" -DUSE_HAL_DRIVER -DSTM32F411xE -D__weak=""__attribu
te__((weak))"" -D__packed=""__attribute__((__packed__))"" -DUSE_HAL_DRIVER -DSTM32F411xE', '
CUBE LD script ', 'STM32F411RETx_FLASH.ld')

2CUBE project name: ('Test2','
2CUBE MCU: ', 'STM32F411RETx', '
2CUBE CFLAGS: ', '-mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard', '
2CUBE DEFs: ','-D__weak=__attribute__((weak))-D__packed=__attribute__((__packed__))-DUSE_HAL_DRIVER-DSTM32F411xE-D__weak=
__attribute__((weak))-D__packed=__attribute__((__packed__))-DUSE_HAL_DRIVER-DSTM32F411xE-D__weak=__attribute__((weak))-D_
_packed=__attribute__((__packed__))-DUSE_HAL_DRIVER-DSTM32F411xE-D__weak=__attribute__((weak))-D__packed=__attribute__((_
_packed__))-DUSE_HAL_DRIVER-DSTM32F411xE','
2CUBE LD script ','STM32F411RETx_FLASH.ld')
Clang!11
222
INCLUDES:

**Comment by improve100** [comment]
ok,i fix it by using python3

**Comment by SL-RU** [comment]
Hello, thanks for the issue, I'll fix that
