### ISSUE TITLE
new function `st-flash`

### ISSUE THREAD

**Issue by KVAnton-WEB** [SL-RU/stm32-emacs#2]
My function is for `st-flash`, maybe it will be useful to someone else. 
I am not creating a pull-request because I am not an expert in elisp, and perhaps this is not the best implementation. (and also I use only Linux)

```
(defun stm32-st-flash (&optional path)
  "st-flash  --format ihex write ${project_name}.hex.  Use existing project path's or use optional arg PATH."
  (interactive)
	(message "st-flash --format ihex write ${project_name}.hex")
  (let ((dir (or path (stm32-get-project-build-dir)))
        (name (stm32-get-project-name))
        (output-buffer (get-buffer-create "*st-flash*")))
    (async-shell-command (concat "cd " dir "; st-flash  --format ihex write " name ".hex") output-buffer)))
```

**Comment by SL-RU** [comment]
Thanks for the proposal but I think it is not necessary because gdb with st-util or openocd gives the same functionality and a lot more. Also two different functions `stm32-flash-to-mcu` and  `stm32-st-flash` with almost the same functionality and almost the same name may confuse someone.
