### ISSUE TITLE
multiple definition

### ISSUE THREAD

**Issue by KVAnton-WEB** [SL-RU/stm32-emacs#5]
/Core/Src/syscalls.c:89: multiple definition of `_exit'; /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/lib/thumb/v7-m/nofp/libnosys.a(_exit.o):/build/newlib-CVVEyx/newlib-3.3.0/build/arm-none-eabi/thumb/v7-m/nofp/libgloss/libnosys/../../../../../../../libgloss/libnosys/_exit.c:17: first defined here

Через скрипты CubeIDE линкуется нормально.

**Comment by SL-RU** [comment]
Нужно удалить файл /Core/Src/syscalls.c или добавить его в CMakeIgnore.txt. Или настоить изменить библиотеку syscalls, по-умолчанию стоит libnosys

**Comment by KVAnton-WEB** [comment]
Спасибо, все получилось 🙏
